-- MySQL Script generated by MySQL Workbench
-- Mon Jan 20 16:16:56 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Comments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Comments` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Comments` (
  `idComments` INT NOT NULL,
  `Comment` VARCHAR(45) NOT NULL,
  `Experiences_idExperiences` INT NOT NULL,
  PRIMARY KEY (`idComments`),
  UNIQUE INDEX `idComments_UNIQUE` (`idComments` ASC) VISIBLE,
  INDEX `fk_Comments_Experiences1_idx` (`Experiences_idExperiences` ASC) VISIBLE,
  CONSTRAINT `fk_Comments_Experiences1`
    FOREIGN KEY (`Experiences_idExperiences`)
    REFERENCES `mydb`.`Experiences` (`idExperiences`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Experiences`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Experiences` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Experiences` (
  `idExperiences` INT NOT NULL,
  `personalRating` DECIMAL(3,2) NOT NULL,
  `NumberComments` INT NOT NULL,
  `userRating` DECIMAL(3,2) NOT NULL DEFAULT 0,
  `NumberOfRatings` INT NOT NULL DEFAULT 0,
  `Description` VARCHAR(1200) NOT NULL,
  `Users_idUsers` INT NOT NULL,
  `Trips_idTrips` INT NOT NULL,
  PRIMARY KEY (`idExperiences`),
  UNIQUE INDEX `idPosts_UNIQUE` (`idExperiences` ASC) VISIBLE,
  INDEX `fk_Experiences_Users1_idx` (`Users_idUsers` ASC) VISIBLE,
  INDEX `fk_Experiences_Trips1_idx` (`Trips_idTrips` ASC) VISIBLE,
  CONSTRAINT `fk_Experiences_Users1`
    FOREIGN KEY (`Users_idUsers`)
    REFERENCES `mydb`.`Users` (`idUsers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Experiences_Trips1`
    FOREIGN KEY (`Trips_idTrips`)
    REFERENCES `mydb`.`Trips` (`idTrips`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PhotoIds`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`PhotoIds` ;

CREATE TABLE IF NOT EXISTS `mydb`.`PhotoIds` (
  `idPhotoIds` INT NOT NULL,
  `Experiences_idExperiences` INT NOT NULL,
  `Users_idUsers` INT NOT NULL,
  PRIMARY KEY (`idPhotoIds`, `Experiences_idExperiences`),
  INDEX `fk_PhotoIds_Experiences1_idx` (`Experiences_idExperiences` ASC) VISIBLE,
  INDEX `fk_PhotoIds_Users1_idx` (`Users_idUsers` ASC) VISIBLE,
  CONSTRAINT `fk_PhotoIds_Experiences1`
    FOREIGN KEY (`Experiences_idExperiences`)
    REFERENCES `mydb`.`Experiences` (`idExperiences`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PhotoIds_Users1`
    FOREIGN KEY (`Users_idUsers`)
    REFERENCES `mydb`.`Users` (`idUsers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Trips`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Trips` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Trips` (
  `idTrips` INT NOT NULL,
  `IsPrivate` TINYINT NOT NULL DEFAULT 0,
  `Location` VARCHAR(200) NOT NULL,
  `Users_idUsers` INT NOT NULL,
  PRIMARY KEY (`idTrips`),
  INDEX `fk_Trips_Users1_idx` (`Users_idUsers` ASC) VISIBLE,
  CONSTRAINT `fk_Trips_Users1`
    FOREIGN KEY (`Users_idUsers`)
    REFERENCES `mydb`.`Users` (`idUsers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Users` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Users` (
  `idUsers` INT NOT NULL,
  `UserName` VARCHAR(45) NOT NULL,
  `PostsMade` INT NOT NULL,
  PRIMARY KEY (`idUsers`),
  UNIQUE INDEX `idUsers_UNIQUE` (`idUsers` ASC) VISIBLE,
  UNIQUE INDEX `UserName_UNIQUE` (`UserName` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
